This folder has scripts that generates meeting times,
for random walk Metropolis Hastings (RWMH), Metropolis adjusted Langevin Algorithm (MALA),
and Hamiltonian Monte Carlo (HMC). The target is a multivariate Gaussian in varying dimensions.
The plots are generated by scaling.plots.R, once the other scripts have been run.

Note: the script have a number of repeats parameter, set to 100. With this setting, the three scripts
can be run in a few minutes. For the article we have set this number to 1000, which took 10 times longer.
The resulting figures are pretty much the same.
