# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logcosh <- function(x) {
    .Call('_debiasedhmc_logcosh', PACKAGE = 'debiasedhmc', x)
}

gaussian_max_couplingC <- function(mu1, mu2, Sigma1, Sigma2) {
    .Call('_debiasedhmc_gaussian_max_couplingC', PACKAGE = 'debiasedhmc', mu1, mu2, Sigma1, Sigma2)
}

gaussian_max_coupling_cholesky <- function(mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2) {
    .Call('_debiasedhmc_gaussian_max_coupling_cholesky', PACKAGE = 'debiasedhmc', mu1, mu2, Cholesky1, Cholesky2, Cholesky_inverse1, Cholesky_inverse2)
}

#' @export
coxprocess_loglikelihood <- function(x, counts, area) {
    .Call('_debiasedhmc_coxprocess_loglikelihood', PACKAGE = 'debiasedhmc', x, counts, area)
}

estimator_bin <- function(c_chains, component, lower, upper, k, K) {
    .Call('_debiasedhmc_estimator_bin', PACKAGE = 'debiasedhmc', c_chains, component, lower, upper, k, K)
}

#' @export
gradlognormal <- function(x, mean, precision) {
    .Call('_debiasedhmc_gradlognormal', PACKAGE = 'debiasedhmc', x, mean, precision)
}

rinvgaussian_c <- function(n, mu, lambda) {
    .Call('_debiasedhmc_rinvgaussian_c', PACKAGE = 'debiasedhmc', n, mu, lambda)
}

rinvgaussian_coupled_c <- function(mu1, mu2, lambda1, lambda2) {
    .Call('_debiasedhmc_rinvgaussian_coupled_c', PACKAGE = 'debiasedhmc', mu1, mu2, lambda1, lambda2)
}

logistic_logtarget_c <- function(chain_state, Y, X, lambda) {
    .Call('_debiasedhmc_logistic_logtarget_c', PACKAGE = 'debiasedhmc', chain_state, Y, X, lambda)
}

logistic_gradlogtarget_c <- function(chain_state, Y, X, lambda) {
    .Call('_debiasedhmc_logistic_gradlogtarget_c', PACKAGE = 'debiasedhmc', chain_state, Y, X, lambda)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call('_debiasedhmc_rmvnorm', PACKAGE = 'debiasedhmc', nsamples, mean, covariance)
}

rmvnorm_cholesky <- function(nsamples, mean, cholesky) {
    .Call('_debiasedhmc_rmvnorm_cholesky', PACKAGE = 'debiasedhmc', nsamples, mean, cholesky)
}

dmvnorm <- function(x, mean, covariance) {
    .Call('_debiasedhmc_dmvnorm', PACKAGE = 'debiasedhmc', x, mean, covariance)
}

dmvnorm_cholesky_inverse <- function(x, mean, cholesky_inverse) {
    .Call('_debiasedhmc_dmvnorm_cholesky_inverse', PACKAGE = 'debiasedhmc', x, mean, cholesky_inverse)
}

rtmg_coupled <- function(n_, seed_, initial_1, initial_2, numlin_, F_, g_, numquad_, quadratics_) {
    .Call('_debiasedhmc_rtmg_coupled', PACKAGE = 'debiasedhmc', n_, seed_, initial_1, initial_2, numlin_, F_, g_, numquad_, quadratics_)
}

rtmg <- function(n_, seed_, initial_, numlin_, F_, g_, numquad_, quadratics_) {
    .Call('_debiasedhmc_rtmg', PACKAGE = 'debiasedhmc', n_, seed_, initial_, numlin_, F_, g_, numquad_, quadratics_)
}

